OH = 'datasets/Office-Home'
OF = 'datasets/Office31'
TC = 'datasets/TextCategorization'
#----------------------------------------------------------------#
# Office-Home Datasets
SArD = OH + '/Source_Ar_DeCAF6.mat'
SArR = OH + '/Source_Ar_ResNet50.mat'
SArS = OH + '/Source_Ar_SURF.mat'
SClD = OH + '/Source_Cl_DeCAF6.mat'
SClR = OH + '/Source_Cl_ResNet50.mat'
SClS = OH + '/Source_Cl_SURF.mat'
SPrD = OH + '/Source_Pr_DeCAF6.mat'
SPrR = OH + '/Source_Pr_ResNet50.mat'
SPrS = OH + '/Source_Pr_SURF.mat'
SReD = OH + '/Source_Re_DeCAF6.mat'
SReR = OH + '/Source_Re_ResNet50.mat'
SReS = OH + '/Source_Re_SURF.mat'
#------------------------------#
TArD = OH + '/Target_Ar_DeCAF6.mat'
TArR = OH + '/Target_Ar_ResNet50.mat'
TArS = OH + '/Target_Ar_SURF.mat'
TClD = OH + '/Target_Cl_DeCAF6.mat'
TClR = OH + '/Target_Cl_ResNet50.mat'
TClS = OH + '/Target_Cl_SURF.mat'
TPrD = OH + '/Target_Pr_DeCAF6.mat'
TPrR = OH + '/Target_Pr_ResNet50.mat'
TPrS = OH + '/Target_Pr_SURF.mat'
TReD = OH + '/Target_Re_DeCAF6.mat'
TReR = OH + '/Target_Re_ResNet50.mat'
TReS = OH + '/Target_Re_SURF.mat'
#----------------------------------------------------------------#
# Office31 Datasets
SAD = OF + '/Source_A31_DeCAF6.mat'
SAR = OF + '/Source_A31_ResNet50.mat'
SAS = OF + '/Source_A31_SURF.mat'
SDD = OF + '/Source_D31_DeCAF6.mat'
SDR = OF + '/Source_D31_ResNet50.mat'
SDS = OF + '/Source_D31_SURF.mat'
SWD = OF + '/Source_W31_DeCAF6.mat'
SWR = OF + '/Source_W31_ResNet50.mat'
SWS = OF + '/Source_W31_SURF.mat'
#------------------------------#
TAD = OF + '/Target_A31_DeCAF6.mat'
TAR = OF + '/Target_A31_ResNet50.mat'
TAS = OF + '/Target_A31_SURF.mat'
TDD = OF + '/Target_D31_DeCAF6.mat'
TDR = OF + '/Target_D31_ResNet50.mat'
TDS = OF + '/Target_D31_SURF.mat'
TWD = OF + '/Target_W31_DeCAF6.mat'
TWR = OF + '/Target_W31_ResNet50.mat'
TWS = OF + '/Target_W31_SURF.mat'
#----------------------------------------------------------------#
# TextCategorization
E = TC + '/Source_EN.mat'
F = TC + '/Source_FR.mat'
G = TC + '/Source_GR.mat'
I = TC + '/Source_IT.mat'
S5 = TC + '/Target_SP_5.mat'
#----------------------------------------------------------------#
